### ISSUE TITLE
Fix division by zero

### ISSUE THREAD

**Issue by GabeGiro** [GabeGiro/EasyApplyJobsBot#50]
```
2024-08-27 10:51:29 ❌ Error ❌ Unhandled exception in startApplying: division by zero
2024-08-27 10:51:29 Traceback (most recent call last):
2024-08-27 10:51:29   File "/app/EasyApplyJobsBot/linkedin.py", line 104, in startApplying
2024-08-27 10:51:29     jobCounter = self.processJob(jobID=job.linkedinJobId, jobCounter=jobCounter)
2024-08-27 10:51:29                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 10:51:29   File "/app/EasyApplyJobsBot/linkedin.py", line 153, in processJob
2024-08-27 10:51:29     jobCounter = self.handleJobPost(
2024-08-27 10:51:29                  ^^^^^^^^^^^^^^^^^^^
2024-08-27 10:51:29   File "/app/EasyApplyJobsBot/linkedin.py", line 252, in handleJobPost
2024-08-27 10:51:29     jobCounter = self.handleMultiplePages(jobPage, jobProperties, jobCounter)
2024-08-27 10:51:29                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27 10:51:29   File "/app/EasyApplyJobsBot/linkedin.py", line 449, in handleMultiplePages
2024-08-27 10:51:29     applyPages = math.ceil(100 / percentage) - 2
2024-08-27 10:51:29                            ~~~~^~~~~~~~~~~~
2024-08-27 10:51:29 ZeroDivisionError: division by zero
```

**Comment by GabeGiro** [comment]
Still an issue:

```
2024-09-04 12:50:01 Traceback (most recent call last):
2024-09-04 12:50:01   File "/app/EasyApplyJobsBot/linkedin.py", line 106, in startApplying
2024-09-04 12:50:01     jobCounter = self.processJob(jobID=job.linkedinJobId, jobCounter=jobCounter)
2024-09-04 12:50:01                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04 12:50:01   File "/app/EasyApplyJobsBot/linkedin.py", line 155, in processJob
2024-09-04 12:50:01     jobCounter = self.handleJobPost(
2024-09-04 12:50:01                  ^^^^^^^^^^^^^^^^^^^
2024-09-04 12:50:01   File "/app/EasyApplyJobsBot/linkedin.py", line 251, in handleJobPost
2024-09-04 12:50:01     jobCounter = self.handleMultiplePages(jobPage, jobProperties, jobCounter)
2024-09-04 12:50:01                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04 12:50:01   File "/app/EasyApplyJobsBot/linkedin.py", line 460, in handleMultiplePages
2024-09-04 12:50:01     applyPages = math.ceil(100 / percentage) - 2
2024-09-04 12:50:01                            ~~~~^~~~~~~~~~~~
2024-09-04 12:50:01 ZeroDivisionError: division by zero
```
