### ISSUE TITLE
Fix the percentage bug

### ISSUE THREAD

**Issue by GabeGiro** [GabeGiro/EasyApplyJobsBot#78]
```
2024-11-12 15:02:15 ❌ Error ❌ Unhandled exception in startApplying: invalid literal for int() with base 10: '14.000000000000002'
2024-11-12 15:02:16 ---Took: 12 minute(s).
2024-11-12 15:02:16 Sleeping for 75.08218045494255 seconds.
2024-11-12 15:02:15 Traceback (most recent call last):
2024-11-12 15:02:15   File "/app/EasyApplyJobsBot/linkedin.py", line 106, in startApplying
2024-11-12 15:02:15     jobCounter = self.processJob(jobID=job.linkedinJobId, jobCounter=jobCounter)
2024-11-12 15:02:15                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 15:02:15   File "/app/EasyApplyJobsBot/linkedin.py", line 155, in processJob
2024-11-12 15:02:15     jobCounter = self.handleJobPost(
2024-11-12 15:02:15                  ^^^^^^^^^^^^^^^^^^^
2024-11-12 15:02:15   File "/app/EasyApplyJobsBot/linkedin.py", line 251, in handleJobPost
2024-11-12 15:02:15     jobCounter = self.handleMultiplePages(jobPage, jobProperties, jobCounter)
2024-11-12 15:02:15                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 15:02:15   File "/app/EasyApplyJobsBot/linkedin.py", line 459, in handleMultiplePages
2024-11-12 15:02:15     percentage = int(comPercentage)
2024-11-12 15:02:15                  ^^^^^^^^^^^^^^^^^^
2024-11-12 15:02:15 ValueError: invalid literal for int() with base 10: '14.000000000000002'
```

**Comment by joaopellcorr** [comment]
This error indicates that the program tried to convert the value '14.000000000000002' to an integer using the int() function, but failed because the int() function only accepts whole numbers and not decimals (or floats). In this case, the value is in floating-point format (float) with many decimal places.

in line 459, instead of:
percentage = int(comPercentage)
use:
int(round(float(comPercentage)))

**Comment by GabeGiro** [comment]
@joaopellcorr if you want, you can open a PR and after I test it, I would merge it. And the line would probably be:
`int(round(comPercentage))`

**Comment by GabeGiro** [comment]
Done
