### ISSUE TITLE
Fix percentage element not being found

### ISSUE THREAD

**Issue by GabeGiro** [GabeGiro/EasyApplyJobsBot#79]
```
2024-11-14 12:07:34 ❌ Error ❌ Unhandled exception in startApplying: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//progress[contain
2024-11-14 12:07:34 Traceback (most recent call last):
2024-11-14 12:07:34   File "/app/EasyApplyJobsBot/linkedin.py", line 106, in startApplying
2024-11-14 12:07:34     jobCounter = self.processJob(jobID=job.linkedinJobId, jobCounter=jobCounter)
2024-11-14 12:07:34                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-14 12:07:34   File "/app/EasyApplyJobsBot/linkedin.py", line 155, in processJob
2024-11-14 12:07:34     jobCounter = self.handleJobPost(
2024-11-14 12:07:34                  ^^^^^^^^^^^^^^^^^^^
2024-11-14 12:07:34   File "/app/EasyApplyJobsBot/linkedin.py", line 251, in handleJobPost
2024-11-14 12:07:34     jobCounter = self.handleMultiplePages(jobPage, jobProperties, jobCounter)
2024-11-14 12:07:34                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-14 12:07:34   File "/app/EasyApplyJobsBot/linkedin.py", line 457, in handleMultiplePages
2024-11-14 12:07:34     percentageElement = self.driver.find_element(By.XPATH, constants.multiplePagePercentageXPATH)
2024-11-14 12:07:34                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-14 12:07:34   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 766, in find_element
2024-11-14 12:07:34     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2024-11-14 12:07:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-14 12:07:34   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
2024-11-14 12:07:34     self.error_handler.check_response(response)
2024-11-14 12:07:34   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-11-14 12:07:34     raise exception_class(message, screen, stacktrace)
2024-11-14 12:07:34 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//progress[contains(@class, 'artdeco-completeness-meter-linear__progress-element')]"}
2024-11-14 12:07:34   (Session info: chrome-headless-shell=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

**Comment by GabeGiro** [comment]
This might have happened due to internet connection error... Checking internet connection might be a good thing to do

**Comment by GabeGiro** [comment]
@Zedespook why are there 2 PRs linked to this issue? I see which one I like more but please be more tidy with the issue/PR linking. After you tidy things up for all your current work, then ping me on Slack to start reviewing. Make my life easier to help you move forward.
